### ISSUE TITLE
Extending CI compatibility 

### ISSUE THREAD

**Issue by hmontazeri** [doshisid/git-ssh-key#1]
Hi, 

I was wondering how you would add an self hosted gitlab for example? 
Is there a way to set up your custom CI Integration?

**Comment by sidoshi** [comment]
Currently, it is not possible to setup ssh keys for self hosted git service. 

Though, It can be made so that two extra env variables are read: `GIT_SSH_KEY` and `GIT_HOST`. 
Then we can provide the key for self-hosted gitlab for example in `GIT_SSH_KEY` and the host IP or URL in `GIT_HOST`. 

I will work on it soon. 👍

**Comment by hmontazeri** [comment]
Sounds nice! I think a lot of companies are hosting their own platforms and this is a very cool tool!

**Comment by sidoshi** [comment]
Solved in the [v1.1](https://github.com/doshisid/git-ssh-key/commit/fbdfad9a70a45bff4a3a6c8d14b57c3250de35ae) release.

> git-ssh-key needs two things to function properly. The private key and the url of the git host. You can provide any number of private key and host url pairs by setting the proper environment variables. git-ssh-key looks for a pattern in env variables to get pairs of private keys and hosts.
> 
> The pattern for private keys is: GIT_SSH_KEY_XXXXX
> 
> Example:- GIT_SSH_KEY_GITHUB GIT_SSH_KEY_GITLAB GIT_SSH_KEY_BUTBUCKET GIT_SSH_KEY_COMPANY_GITLAB
> 
> This variables need to be set with appropriate private keys encoded in base64.
> 
> The pattern for host urls is:- GIT_SSH_HOST_XXX
> 
> Example:- GIT_SSH_HOST_GITHUB='github.com' GIT_SSH_HOST_GITLAB='gitlab.com' GIT_SSH_HOST_BUTBUCKET='bitbucket.org' GIT_SSH_HOST_SELF_GITLAB=gitlab.self.com
> 
> For every host, there must be a corresponding private key and vice versa with an exception to few popular hosts.
> 
> You don't need to provide host urls for Github, Gitlab or Bitbucket. They are set by default to github.com, 'gitlab.com' and 'bitbucket.org' respectively. Though if you do provide host urls for these services, provided urls will override the default urls.
